### ISSUE TITLE
Add Installation-Guide to Readme

### ISSUE THREAD

**Issue by DavidPhilip** [Bosnadev/Database#1]
Hey, I included your stuff per autoload in my Laravel project (installing via composer and vcs doesn't work). It seems to boot nicely though I still get an error when using the new types in my migrations like ```$table->uuid('id')``` Please, could you guide me through how to set it up correctly or how it's intended to be included in a laravel project?

**Comment by DavidPhilip** [comment]
Hi! Could you please upload your package to https://packagist.org or would you give me the permission to do so?

**Comment by mirzap** [comment]
Hi, sorry I didn't submit the package because it lacks some things i plan to do. Now it's submited.
I renemed the package, and still I'm not sure what to keep. 

Anyway, you should be able to install it now by adding:

    "bosnadev/database": "0.*"

to the composer require section. If there is some problem with packagist, then you can add repository section above require. Here is that part of my composer.json:

	"repositories": [
	  {
		"type": "vcs",
		"url": "https://github.com/Bosnadev/sentry"
	  },
	  {
		"type": "vcs",
		"url": "https://github.com/Bosnadev/Eloquently"
	  }
	],
	"require": {
		"laravel/framework": "5.0.*",
	  	"illuminate/html": "5.*",

	  	"cartalyst/sentry": "~3.0",

	  	"predis/predis": "~1.0",
	  	"pda/pheanstalk": "~3.0",

	  	"bosnadev/database": "0.*"
	},

**Comment by mirzap** [comment]
Also, I'll try to add some documentation in the next week or two.

**Comment by DavidPhilip** [comment]
Thanks for your reply. I will add it to my dependencies as soon as possible!

**Comment by mcka** [comment]
Hey +1 for documentation

**Comment by rtconner** [comment]
+1 for documentation plz

**Comment by mirzap** [comment]
I'm busy right now, but I'll try to add some doc ;)

**Comment by adaojunior** [comment]
+ 1

**Comment by Roquie** [comment]
+1

**Comment by rap2hpoutre** [comment]
+1 for doc ;)
Anyway, we can make PR too. Who wants? (not me, I'm lazy!)
