### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by jaysson** [bosnadev/database#35]
Any plans to support Laravel 6?

**Comment by anx-mwutte** [comment]
+1

**Comment by gueroverde** [comment]
I made a pull request for laravel6 support #36

**Comment by mirzap** [comment]
Hi, thank you. I'll review today and tag a new version.

**Comment by mirzap** [comment]
I should be now, 0.19.x supports Laravel 6.x, latest is 0.19.1
