### ISSUE TITLE
Unsigned causes Postgres error when used with Integer or BigInteger

### ISSUE THREAD

**Issue by faytekin** [bosnadev/database#48]
Laravel Version: 8.48.1
PHP Version: 8.0.1

Migrations that mix `integer()` (or `bigInteger()`) with `unsigned()` no longer migrate, but throw an error with Postgres error.

```php
Schema::create('broken_primary', function (Blueprint $table) {
    $table->integer('broken_id')->unsigned()->primary();
    $table->timestamps();
});
```

**Comment by studnitz** [comment]
This was fixed with https://github.com/laravel/framework/pull/37826, so no need for this anymore.
